---
- name: Setup preference for Debian Unstable repo
  copy:
    src: debian-apt-preferences
    dest: /etc/apt/preferences.d/limit-unstable
    owner: root
    group: root
    mode: 0644

- name: Add Debian Unstable key
  apt_key:
    keyserver: pgpkeys.mit.edu
    id: "{{ item }}"
    state: present
  with_items:
    - 7638D0442B90D010
    - 04EE7237B7D453EC

- name: Add Debian Unstable repo
  apt_repository:
    repo: "deb http://deb.debian.org/debian unstable main"
    state: present
    update_cache: yes

- name: Install Wireguard & deps
  apt:
    name:
      - "{{ kernel_headers_package | default('linux-headers-'+ansible_kernel) }}"
      - wireguard-tools
      - wireguard-dkms
    state: present
